# .github/workflows/scrape.yml (Corrected Permissions Version)
name: Scrape Reddit Wiki and Generate API File

on:
  schedule:
    - cron: '0 6 * * *' # Runs daily at 6:00 AM UTC
  workflow_dispatch: # Allows manual runs

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest

    # --- ADD THIS BLOCK ---
    # This grants the GITHUB_TOKEN write permission for the job, allowing it to push changes.
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run Scraper
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: python scrape_wiki.py ./data

      - name: Commit and Push to Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Updated watch order data files"
          file_pattern: data/*.json
